import math

RADIAL_ROTATION = (3 * math.pi) / 2
NORMAL_ROTATION = math.pi / 2

MATERIAL_CONFIG = {
    "1": {
        'price':'2288',
        "name": "桶珠手串",
        "background": [
            {"glb": "/static/models/圈圈45.gltf", "name": "桶珠手串", "length": 14},
            {"glb": "/static/models/圈圈47.gltf", "name": "桶珠手串", "length": 15},
            {"glb": "/static/models/圈圈51.gltf", "name": "桶珠手串", "length": 16},
            {"glb": "/static/models/圈圈54.gltf", "name": "桶珠手串", "length": 17},
            {"glb": "/static/models/圈圈57.gltf", "name": "桶珠手串", "length": 18},
            {"glb": "/static/models/圈圈60.gltf", "name": "桶珠手串", "length": 19},
        ],
        "product": [
            {
                "glb": "/static/models/321.glb",
                "name": "磨砂珠",
                "weight": "1",
                "width": "6mm",
                "rotation": RADIAL_ROTATION,
                "rotationAxis": "radial",
                "png": "/static/models/磨砂珠6mm.png",
            },
            {
                "glb": "/static/models/321.glb",
                "name": "磨砂珠",
                "weight": "1",
                "width": "4mm",
                "rotation": RADIAL_ROTATION,
                "rotationAxis": "radial",
                "png": "/static/models/磨砂珠4mm.png",
            },
            {
                "glb": "/static/models/绿玛瑙1.gltf",
                "name": "绿玛瑙",
                "weight": "2",
                "width": "6mm",
                "rotation": NORMAL_ROTATION,
                "rotationAxis": "normal",
                "png": "/static/models/绿玛瑙1.png",
            },
            {
                "glb": "/static/models/绿玛瑙1.gltf",
                "name": "金曜石",
                "weight": "2",
                "width": "6mm",
                "rotation": NORMAL_ROTATION,
                "rotationAxis": "normal",
                "png": "/static/models/金耀石.png",
            },
            {
                "glb": "/static/models/绿玛瑙1.gltf",
                "name": "红玛瑙",
                "weight": "2",
                "width": "6mm",
                "rotation": NORMAL_ROTATION,
                "rotationAxis": "normal",
                "png": "/static/models/红玛瑙.png",
            },
            {
                "glb": "/static/models/绿玛瑙1.gltf",
                "name": "黑玛瑙",
                "weight": "2",
                "width": "6mm",
                "rotation": NORMAL_ROTATION,
                "rotationAxis": "normal",
                "png": "/static/models/黑玛瑙.png",
            },
            {
                "glb": "/static/models/绿玛瑙1.gltf",
                "name": "绿玛瑙",
                "weight": "2",
                "width": "6mm",
                "rotation": NORMAL_ROTATION,
                "rotationAxis": "normal",
                "png": "/static/models/绿玛瑙1.png",
            },
            {
                "glb": "/static/models/蓝玛瑙1.gltf",
                "name": "蓝玛瑙",
                "weight": "2",
                "width": "6mm",
                "rotation": NORMAL_ROTATION,
                "rotationAxis": "normal",
                "png": "/static/models/蓝玛瑙.png",
            },
            {
                "glb": "/static/models/绿玛瑙1.gltf",
                "name": "虎眼珠",
                "weight": "2",
                "width": "6mm",
                "rotation": NORMAL_ROTATION,
                "rotationAxis": "normal",
                "png": "/static/models/虎眼珠.png",
            },
            {
                "glb": "/static/models/绿玛瑙1.gltf",
                "name": "白玛瑙",
                "weight": "2",
                "width": "6mm",
                "rotation": NORMAL_ROTATION,
                "rotationAxis": "normal",
                "png": "/static/models/白玛瑙.png",
            },
        ],
    },
    "2": {
        'price':'2188',
        "name": "药片石手串",
        "background": [
            {"glb": "/static/models/圈圈45.gltf", "name": "桶珠手串", "length": 14},
            {"glb": "/static/models/圈圈47.gltf", "name": "桶珠手串", "length": 15},
            {"glb": "/static/models/圈圈51.gltf", "name": "桶珠手串", "length": 16},
            {"glb": "/static/models/圈圈54.gltf", "name": "桶珠手串", "length": 17},
            {"glb": "/static/models/圈圈57.gltf", "name": "桶珠手串", "length": 18},
            {"glb": "/static/models/圈圈60.gltf", "name": "桶珠手串", "length": 19},
        ],
        "product": [
            {
                "glb": "/static/models/321.glb",
                "name": "药片白玛瑙",
                "weight": "1",
                "width": "4mm",
                "rotation": RADIAL_ROTATION,
                "rotationAxis": "radial",
                "png": "/static/models/药片白玛瑙.png",
            },
            {
                "glb": "/static/models/321.glb",
                "name": "药片黑玛瑙",
                "weight": "1",
                "width": "4mm",
                "rotation": RADIAL_ROTATION,
                "rotationAxis": "radial",
                "png": "/static/models/药片黑玛瑙.png",
            },
            {
                "glb": "/static/models/321.glb",
                "name": "药片黑曜石",
                "weight": "1",
                "width": "4mm",
                "rotation": RADIAL_ROTATION,
                "rotationAxis": "radial",
                "png": "/static/models/药片黑曜石.png",
            },
            {
                "glb": "/static/models/321.glb",
                "name": "药片红玛瑙",
                "weight": "1",
                "width": "4mm",
                "rotation": RADIAL_ROTATION,
                "rotationAxis": "radial",
                "png": "/static/models/药片红玛瑙.png",
            },
            {
                "glb": "/static/models/321.glb",
                "name": "药片虎眼",
                "weight": "1",
                "width": "4mm",
                "rotation": RADIAL_ROTATION,
                "rotationAxis": "radial",
                "png": "/static/models/药片虎眼.png",
            },
            {
                "glb": "/static/models/321.glb",
                "name": "药片蓝玛瑙",
                "weight": "1",
                "width": "4mm",
                "rotation": RADIAL_ROTATION,
                "rotationAxis": "radial",
                "png": "/static/models/药片蓝玛瑙.png",
            },
            {
                "glb": "/static/models/321.glb",
                "name": "药片绿玛瑙",
                "weight": "1",
                "width": "4mm",
                "rotation": RADIAL_ROTATION,
                "rotationAxis": "radial",
                "png": "/static/models/药片绿玛瑙.png",
            },
        ],
    },
}

__all__ = ["MATERIAL_CONFIG"]
